version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ${CODE_PATH_HOST}/${APP_NAME}:/var/www
      - ./php/${PHP_INI}:/usr/local/etc/php/conf.d/${PHP_INI}
    networks:
      - backend

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "${NGINX_PORT}:80"
      - "443:443"
    volumes:
      - ${CODE_PATH_HOST}/${APP_NAME}:/var/www
      - ./nginx/${NGINX_CONF}/:/etc/nginx/conf.d/
    networks:
      - backend
### MySQL ################################################
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ./mysql/${MYSQL_CNF}:/etc/mysql/my.cnf
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend
### phpMyAdmin ###########################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
    restart: always
    ports:
      - ${PMA_PORT}:80
    restart: always
    depends_on:
       - mysql
    volumes:
      - /sessions
    networks:
      backend:
### Redis ################################################
  redis:
    build: ./redis    
    container_name: redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

volumes:
  db-data:
networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 172.16.100.0/24